eureka:
    client:
        register-with-eureka: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    instance:
        hostname: discovery-server
server:
    port: 9001
spring:
    application:
        name: eureka-server
