eureka:
  client:
    eureka-service-url-defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 9001
spring:
  application:
    name: eurekaserver
